#!/usr/bin/env node
/**
 * Fetches the current TLD list from IANA and writes src/data/tlds.ts.
 *
 * Exits early (unchanged) if IANA's Last-Updated timestamp hasn't changed.
 * Run with: node scripts/update-tlds.mjs
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const IANA_URL = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt";
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = join(__dirname, "../src/data/tlds.ts");

const response = await fetch(IANA_URL);
if (!response.ok) throw new Error(`Failed to fetch IANA TLD list: HTTP ${response.status}`);
const text = await response.text();

const lines = text.split("\n");
const header = lines[0] ?? "";
const match = header.match(/Last Updated (.+UTC)/);
const lastUpdated = match ? new Date(match[1]).toISOString() : new Date().toISOString();

const tlds = lines
  .filter((line) => line && !line.startsWith("#"))
  .map((line) => line.trim().toLowerCase())
  .filter(Boolean);

// Exit early if the IANA timestamp hasn't changed
if (existsSync(OUT_FILE)) {
  const existing = readFileSync(OUT_FILE, "utf-8");
  if (existing.includes(`"${lastUpdated}"`)) {
    console.log(`TLD list is already up to date (${lastUpdated}).`);
    process.exit(0);
  }
}

mkdirSync(dirname(OUT_FILE), { recursive: true });

const content =
  [
    "// Auto-generated by scripts/update-tlds.mjs — do not edit manually.",
    `export const lastUpdated = "${lastUpdated}";`,
    "export const tlds: string[] = [",
    ...tlds.map((t) => `  "${t}",`),
    "];",
  ].join("\n") + "\n";

writeFileSync(OUT_FILE, content, "utf-8");
console.log(`Updated: ${tlds.length} TLDs, last updated ${lastUpdated}`);
